### ISSUE TITLE
Singleton Pattern

### ISSUE THREAD

**Issue by marminthibaut** [cogitoTeam/IA_a_cognitive_approach#10]
Je propose que chacune des parties (et éventuellement sous-partie) soit accessible via une classe singleton générale, permettant de getter directement le bon module.

Ça me paraît être la solution la plus adaptée, mais vu qu'elle nous concerne tous et que je ne suis pas très fort en prog, j'en appelle à vos compétences :p

**Comment by sipi** [comment]
Ok, je m'en charge.
Je crée ça sous le nom IA.
