### ISSUE TITLE
Incompréhensions

### ISSUE THREAD

**Issue by marminthibaut** [cogitoTeam/IA_a_cognitive_approach#16]
J'essaye de tester la mémoire mais je ne comprend rien à certaines classes. Je n'ai pourtant pas l'impression d'être complètement demeuré..

Je parle notamment de la classe Agent située dans le paquage agent, qui imbrique 5 classes (beurk) et qui ne possède **aucune javadoc**.

**Comment by marminthibaut** [comment]
En faite j'ai pigé mais c'est vraiment dégueulasse..

**Comment by wilbefast** [comment]
Tu parles soit de Percept, soit d'Action, mais pas d'Agent: j'ai fait le JD
avant de partir.
https://github.com/marminthibaut/artificial_consciousness/blob/master/App/artificial_consciousness/src/agent/Agent.javaCes
deux classes sont simplement des unions C faites de façon Java, c'est à
dire avec des sous-classes. Et je suis pas d'accord qu'il faut utiliser une
dizaine de .java quand il n'y à que des classes prototypes.

2012/4/11 Thibaut marmin <
reply@reply.github.com
