### ISSUE TITLE
Bug in Minimax or game_service

### ISSUE THREAD

**Issue by marminthibaut** [cogitoTeam/IA_a_cognitive_approach#18]
Je me co sur une partie 10 joueur blanc, je lance un minimax qui obtient la partie 10 joueur noir.

Je joue mon premier coup, et la ça ram (normal) sauf que je suis redirigé sur la partie 8...

**Comment by wilbefast** [comment]
Okey je vais regarder.

2012/4/18 Thibaut marmin <
reply@reply.github.com
