### ISSUE TITLE
Add a finally instruction to close Memory

### ISSUE THREAD

**Issue by sipi** [cogitoTeam/IA_a_cognitive_approach#25]
avr. 21, 2012 12:16:51 PM org.neo4j.kernel.impl.transaction.xaframework.XaLogicalLog doInternalRecovery
Infos: Non clean shutdown detected on log [/home/clement/dev/m1/cogito/neo4j/nioneo_logical.log.1]. Recovery started ...
avr. 21, 2012 12:16:52 PM org.neo4j.kernel.impl.transaction.xaframework.XaLogicalLog doInternalRecovery
Infos: Non clean shutdown detected on log [/home/clement/dev/m1/cogito/neo4j/index/lucene.log.1]. Recovery started ...

**Comment by marminthibaut** [comment]
Normalement l'interruption du process est géré. Peux être as tu killé de processus, au lieu de le terminer..

**Comment by sipi** [comment]
c'est bien possible, mais il me semble que Ctrl-C envoi un SIGTERM et pas un SIGKILL
