### ISSUE TITLE
Enfin des règles supplémentaire

### ISSUE THREAD

**Issue by sipi** [cogitoTeam/IA_a_cognitive_approach#26]
Je pense donc je vais me coucher…

02:38:03,018 DEBUG IntrospectionEngine:66 - I think…
02:38:04,479 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isOpp(x2),isMine(x3),isEdge(x0),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0),aligned(x0,x1,x3),aligned(x3,x1,x0),aligned(x0,x2,x3),aligned(x3,x2,x0),aligned(x1,x2,x3),aligned(x3,x2,x1) --> _rpbs(x0,x1,x2,x3)
02:38:04,925 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isOpp(x1),isEdge(x0),near(x0,x1),near(x1,x0),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2)
02:38:05,161 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isOpp(x0),isMine(x1),near(x0,x1),near(x1,x0) --> _rpbs(x0,x1)
02:38:05,378 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isMine(x2),isMine(x3),isEdge(x0),isEdge(x1),isEdge(x2),isCorner(x0),near(x0,x1),near(x0,x3),near(x1,x0),near(x3,x0),near(x1,x3),near(x1,x2),near(x3,x1),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2,x3)
02:38:05,625 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isOpp(x2),isEdge(x0),isEdge(x1),isCorner(x0),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1) --> _rpbs(x0,x1,x2)
02:38:05,808 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isEdge(x0),isCorner(x0),near(x0,x1),near(x1,x0) --> _rpbs(x0,x1)
02:38:06,688 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isOpp(x0),isMine(x1),isOpp(x2),near(x0,x1),near(x0,x2),near(x1,x0),near(x2,x0),near(x1,x2),near(x2,x1) --> _rpbs(x0,x1,x2)
02:38:06,970 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isOpp(x2),isOpp(x3),isEdge(x0),isEdge(x1),isCorner(x0),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),near(x2,x3),near(x3,x2),aligned(x1,x2,x3),aligned(x3,x2,x1) --> _rpbs(x0,x1,x2,x3)
02:38:07,183 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isOpp(x2),isOpp(x3),isEdge(x0),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),near(x2,x3),near(x3,x2),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2,x3)
02:38:07,372 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isOpp(x1),isMine(x2),isEdge(x2),isEdge(x0),near(x0,x1),near(x1,x0),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2)
02:38:07,630 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isOpp(x0),isOpp(x1),near(x0,x1),near(x1,x0) --> _rpbs(x0,x1)
02:38:07,832 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isMine(x2),isMine(x3),isEdge(x0),isEdge(x1),isEdge(x2),isEdge(x3),isCorner(x0),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0),aligned(x0,x1,x3),aligned(x3,x1,x0),aligned(x0,x2,x3),aligned(x3,x2,x0),aligned(x1,x2,x3),aligned(x3,x2,x1) --> _rpbs(x0,x1,x2,x3)
02:38:08,057 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isMine(x2),isEdge(x0),isEdge(x1),isCorner(x0),near(x0,x1),near(x0,x2),near(x1,x0),near(x2,x0),near(x1,x2),near(x2,x1) --> _rpbs(x0,x1,x2)
02:38:08,297 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isEdge(x0),isEdge(x1),isCorner(x0),near(x0,x1),near(x1,x0) --> _rpbs(x0,x1)
02:38:08,905 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isEmpty(x0),isOpp(x1),isOpp(x2),isEdge(x0),isEdge(x1),isEdge(x2),near(x1,x2),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2)
02:38:09,061 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isOpp(x2),isOpp(x3),isEdge(x0),isEdge(x1),isEdge(x2),isEdge(x3),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),near(x2,x3),near(x3,x2),aligned(x0,x1,x2),aligned(x2,x1,x0),aligned(x0,x1,x3),aligned(x3,x1,x0),aligned(x0,x2,x3),aligned(x3,x2,x0),aligned(x1,x2,x3),aligned(x3,x2,x1) --> _rpbs(x0,x1,x2,x3)
02:38:09,201 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isEmpty(x0),isMine(x1),isMine(x2),isOpp(x3),isEdge(x0),isEdge(x1),isEdge(x2),isEdge(x3),isCorner(x0),near(x1,x2),near(x2,x1),near(x2,x3),near(x3,x2),aligned(x0,x1,x2),aligned(x2,x1,x0),aligned(x0,x1,x3),aligned(x3,x1,x0),aligned(x0,x2,x3),aligned(x3,x2,x0),aligned(x1,x2,x3),aligned(x3,x2,x1) --> _rpbs(x0,x1,x2,x3)
02:38:09,309 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isOpp(x1),isMine(x2),isEdge(x0),isEdge(x1),near(x0,x2),near(x0,x1),near(x2,x0),near(x1,x0) --> _rpbs(x0,x1,x2)
02:38:09,444 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isOpp(x0),isOpp(x1),isEdge(x0),isEdge(x1),near(x0,x1),near(x1,x0) --> _rpbs(x0,x1)
02:38:09,654 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isMine(x2),isMine(x3),isEdge(x0),isEdge(x1),isEdge(x2),near(x0,x1),near(x1,x0),near(x1,x2),near(x1,x3),near(x2,x1),near(x3,x1),near(x2,x3),near(x3,x2),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2,x3)
02:38:09,939 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isMine(x2),isEdge(x0),isEdge(x1),isEdge(x2),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2)
02:38:10,096 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isEdge(x0),isEdge(x1),near(x0,x1),near(x1,x0) --> _rpbs(x0,x1)
02:38:10,707 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isOpp(x0),isOpp(x1),isOpp(x2),isMine(x3),isEdge(x0),near(x0,x1),near(x1,x0),near(x1,x2),near(x1,x3),near(x2,x1),near(x3,x1),near(x2,x3),near(x3,x2),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2,x3)
02:38:10,859 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isOpp(x1),isOpp(x2),isEdge(x0),isEdge(x1),isEdge(x2),near(x1,x2),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2)
02:38:10,987 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isOpp(x1),isOpp(x2),isOpp(x3),isEdge(x0),isEdge(x1),isEdge(x2),near(x0,x3),near(x0,x1),near(x3,x0),near(x1,x0),near(x1,x2),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2,x3)
02:38:11,146 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isOpp(x0),isMine(x1),isMine(x2),isEdge(x2),isEdge(x0),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0),aligned(x0,x1,x3),aligned(x3,x1,x0),aligned(x0,x2,x3),aligned(x3,x2,x0) --> _rpbs(x0,x1,x2,x3)
02:38:11,352 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isOpp(x1),isOpp(x2),isEdge(x0),isEdge(x1),isEdge(x2),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2)
02:38:11,556 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isOpp(x0),isOpp(x1),isEdge(x0),isEdge(x1),near(x0,x1),near(x1,x0) --> _rpbs(x0,x1)
02:38:11,793 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isMine(x2),isMine(x3),isEdge(x0),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0),aligned(x0,x1,x3),aligned(x3,x1,x0),aligned(x0,x2,x3),aligned(x3,x2,x0),aligned(x1,x2,x3),aligned(x3,x2,x1) --> _rpbs(x0,x1,x2,x3)
02:38:11,987 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isMine(x2),isEdge(x0),near(x0,x1),near(x1,x0),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2)
02:38:12,174 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isEmpty(x0),isMine(x1),isEdge(x0),isEdge(x1),near(x0,x1),near(x1,x0) --> _rpbs(x0,x1)
02:38:12,803 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isOpp(x0),isMine(x1),isOpp(x2),near(x0,x2),near(x2,x0),near(x1,x2),near(x2,x1) --> _rpbs(x0,x1,x2)
02:38:13,020 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isOpp(x1),isOpp(x2),isMine(x3),isEdge(x3),near(x0,x1),near(x1,x0),near(x1,x2),near(x1,x3),near(x2,x1),near(x3,x1),near(x2,x3),near(x3,x2),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2,x3)
02:38:13,217 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isOpp(x0),isMine(x1),isMine(x2),isMine(x3),isEdge(x1),isEdge(x0),isCorner(x1),near(x0,x2),near(x0,x1),near(x2,x0),near(x1,x0),near(x2,x3),near(x3,x2),aligned(x0,x2,x3),aligned(x3,x2,x0) --> _rpbs(x0,x1,x2,x3)
02:38:13,437 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isOpp(x0),isMine(x1),isMine(x2),isEdge(x1),isEdge(x2),isEdge(x0),isCorner(x1),near(x0,x1),near(x0,x2),near(x1,x0),near(x2,x0) --> _rpbs(x0,x1,x2)
02:38:13,647 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isOpp(x0),isMine(x1),isEdge(x1),isEdge(x0),near(x0,x1),near(x1,x0) --> _rpbs(x0,x1)
02:38:13,820 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isMine(x2),isMine(x3),isEdge(x0),isEdge(x3),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0),aligned(x0,x1,x3),aligned(x3,x1,x0),aligned(x0,x2,x3),aligned(x3,x2,x0),aligned(x1,x2,x3),aligned(x3,x2,x1) --> _rpbs(x0,x1,x2,x3)
02:38:14,086 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isMine(x2),isEdge(x0),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2)
02:38:14,286 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isEdge(x0),near(x0,x1),near(x1,x0) --> _rpbs(x0,x1)
02:38:14,942 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isMine(x2),isOpp(x3),near(x0,x1),near(x1,x0),near(x1,x2),near(x1,x3),near(x2,x1),near(x3,x1),near(x2,x3),near(x3,x2),aligned(x0,x1,x3),aligned(x3,x1,x0) --> _rpbs(x0,x1,x2,x3)
02:38:15,154 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isOpp(x1),near(x0,x1),near(x1,x0),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2)
02:38:15,340 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isOpp(x1),near(x0,x1),near(x1,x0) --> _rpbs(x0,x1)
02:38:15,516 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isMine(x2),isOpp(x3),isEdge(x0),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),aligned(x0,x1,x2),aligned(x2,x1,x0),aligned(x0,x1,x3),aligned(x3,x1,x0),aligned(x0,x2,x3),aligned(x3,x2,x0),aligned(x1,x2,x3),aligned(x3,x2,x1) --> _rpbs(x0,x1,x2,x3)
02:38:15,709 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isMine(x2),isEdge(x0),near(x0,x1),near(x1,x0),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2)
02:38:15,929 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isEmpty(x1),isEdge(x0),near(x0,x1),near(x1,x0) --> _rpbs(x0,x1)
02:38:16,651 DEBUG IntrospectionEngine:259 - Add new rpbs:  : isMine(x0),isMine(x1),isOpp(x2),isMine(x3),isEdge(x0),near(x0,x1),near(x1,x0),near(x1,x2),near(x2,x1),near(x2,x3),near(x3,x2),aligned(x0,x1,x2),aligned(x2,x1,x0) --> _rpbs(x0,x1,x2,x3)

**Comment by marminthibaut** [comment]
Oublie pas d'aller voter ;)

Thibaut Marminhttp://sites.google.com/site/marminthibaut/vcard/vcard_Thibaut_Marmin.vcf

Le 22 avril 2012 02:44, 6pi <
reply@reply.github.com

**Comment by sipi** [comment]
C'est fait!
