### ISSUE TITLE
Savoir inné...

### ISSUE THREAD

**Issue by sipi** [cogitoTeam/IA_a_cognitive_approach#4]
J'ai commit une proposition de l'état initial de la mémoire : [download](https://github.com/marminthibaut/artificial_consciousness/blob/master/Docs/Divers/proposition_treillis_de_gallois_inn%C3%A9.pdf?raw=true)

Qu'en pensez vous?

**Comment by wilbefast** [comment]
J'arrive pas à très bien lire, mais rappelle toi: le gain/perte en Reversi n'est pas binaire.

**Comment by sipi** [comment]
A oui, effectivement GAIN et PERTE on rien à foutre là... De plus, des concepts composés uniquement de pions noirs ou de pions blancs peuvent exister.

Q) Qu'elle structure doivent être innées?
*alignement de trois pions?
*bord?
*etc…
