### ISSUE TITLE
Composants Mémoire

### ISSUE THREAD

**Issue by marminthibaut** [cogitoTeam/IA_a_cognitive_approach#8]
[EDIT : remplacer Marked par Graded]
[EDIT : remplacer SB (StateBoard) par AC (AdvancedConcept)]
[EDIT : re-remplacer AC par SB]
[EDIT : tout changé xD]

**Vocabulaire**
- **AbstractBoardState** Etat du plateau, class abstraite
- **RelevantePartialBoardState** : Morceau de plateau qui est pertinant
- **CompleteBoardState** : Etat de plateau complet
## Treillis
-  Attributs (**RelevantPartialBoardState**)
- Concepts (**CompleteBoardState**)
## Mémoire épisodique
- Liste chainée de parties
- Une partie est une liste chainée d'états de **CompleteBoardStates**
## Interface Mémoire primaire
- ### Analysis
  - `List<RelevantPartialBoardState> getRelevantPartialBoardStates()` : Retourne la liste **COMPLETE** des RPBS en mémoire
  - `void putCompleteBoardState(CompleteBoardState cbs,
          List<RelevantPartialBoardState> matching)` : mettre en mémoire un CBS avec la liste des RPBS qui matchent
- ### Reasonning Choice
  - `List<Pair<CompleteBoardState, Float>> getGradedCompleteBoardState()` : Retourne la liste des CBS en mémoire primaire, couplés à une note.
  - `void CompleteBoardStateChosen(CompleteBoardState cbs)` : Permet au reasoning de choisir un CBS
  - `void BeginOfGame()` : Indique le début d'une partie (Begin Of Game)
  - `void EndOfGame(FinalGameStatus status, float score)` : Indique la fin d'une partie (End Of Game) : Arg : Un état (Gagné, Perdu, Interrompu) + un score
- ### Reasonning Introspection
  
  A PRECISER MERCII :)
  - **GetWonGamesStateBoards** : Retourne la liste des x derniers AC des parties gagnées en prenant compte de la capacité d'oublie
  - **GetLostGamesStateBoards** : Retourne la liste des x derniers AC des parties perdues en prenant compte de la capacité d'oublie
  - **GetMostActiveStateBoards** : Retourne la liste des x AC les plus actifs en mémoire sémantique
  - _Fonctions de navigation sur les parties stockées en mémoire épisodique (gestion des pointeurs)_
  - **PutRelevantStructure** : Arg : Une relevante structure, qui est ajoutée au contexte du treillis (mais non recalculé pour les SB du contexte)

**Comment by wilbefast** [comment]
Très rapidement: Nam avait pas proposé l'utilisation de formules logiques à la place de BG, justement. Voir: https://github.com/marminthibaut/artificial_consciousness/issues/2

**Comment by marminthibaut** [comment]
Comme j'ai commenté la-bas, on peu appeler BG un graphe représenté par une formule logique, pour moi ça n'est pas une erreur.

**Comment by marminthibaut** [comment]
test rponse email

Thibaut Marminhttp://sites.google.com/site/marminthibaut/vcard/vcard_Thibaut_Marmin.vcf

Le 26 mars 2012 20:38, wilbefast <
reply@reply.github.com

**Comment by marminthibaut** [comment]
héhé vous avez vu juste au dessus : on peu répondre aux mails ;) Mais c'est loin d'être instantané

**Comment by sipi** [comment]
## Reasonning Choice
- List<Pair<CompleteBoardState, Float>> getGradedCompleteBoardState() : Retourne la liste des CBS en mémoire primaire, couplés à une note. 
- void CompleteBoardStateChosen(CompleteBoardState cbs) : Permet au reasoning de choisir un CBS 
- void BeginOfGame() : Indique le début d'une partie (Begin Of Game)
- void EndOfGame(FinalGameStatus status, float score) : Indique la fin d'une partie (End Of Game) : Arg : Un état (Gagné, Perdu, Interrompu) + un score

## Introspection
- GetWonGamesStateBoards : Retourne la liste des x derniers CBS des parties gagnées en prenant compte de la capacité d'oublie
- GetLostGamesStateBoards : Retourne la liste des x derniers CBS des parties perdues en prenant compte de la capacité d'oublie
- Fonctions de navigation sur les parties stockées en mémoire épisodique (gestion des pointeurs) 
- PutRelevantStructure : Arg : Une relevante structure, qui est ajoutée au contexte du treillis (mais non recalculé pour les SB du contexte)
- Il me faut aussi un moyen d'ajouter des attributs au objet du treillis… 
- De donner une valuation positive ou négative à une "relevante structure" (qui influera sur tout les concepts qui la composent)
