### ISSUE TITLE
Une librairie Java pour la logique...

### ISSUE THREAD

**Issue by marminthibaut** [cogitoTeam/IA_a_cognitive_approach#9]
Il faudrait trouver une librairie Java pour les formules logique du premier ordre.

J'ai regardé (très) rapidement et j'ai trouvé **jFuzzyLogic** mais c'est de la logique floue et je ne suis pas sûr que ça convienne pour ce que l'on veut faire. Est-ce que quelqu'un pourrait jeter un coup d'oeil ?

http://jfuzzylogic.sourceforge.net/html/index.html

**Comment by sipi** [comment]
On a juste besoin de faire des homomorphisme, non?
Et dans ce cas, je pense qu'une retouche du code du semestre 1 peu suffir…

**Comment by marminthibaut** [comment]
Comme vous voulez de toute façon ça n'est pas ma partie donc du moment que ça marche (et que c'est rapide à développer :p)
